version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - smtp
    environment:
      MAIL_SERVER: smtp
      MAIL_PORT: 1025
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:root@mysql:3306/bankingapp
      JWT_SECRET: '40a9914ca0dab6c28e25205404a8b74a6f7414e91d7be81a5692f54b612f89d4d4c79223f04a2e67efd5c37925f6cbc88d245edbf8e5fd1abc36cf0ad6ee33a3f596de9978d25f5502c0f249ca2dd7907d600505a3519500939529d544590c7634dd38b61dc7909fc1dc1404ea3b0e085e17bc7164be7d52fb799fed2146917c'
      SECRET_KEY: '7110c8ae51a4b5af97be6534caef90e4bb9bdcb3380af008f90b23a5d1616bf319bc298105da20fe'     
    networks:
      - finservice_network
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bankingapp             
      MYSQL_PASSWORD: root                   
      MYSQL_ROOT_PASSWORD: root              
    ports:
      - "3306:3306"                          
    networks:
      - finservice_network
    restart: always
    
  smtp:
    image: mailhog/mailhog
    container_name: smtp
    ports:
      - "1025:1025"  # MailHog SMTP port
      - "8025:8025"  # MailHog Web interface for viewing mails
    networks:
      - finservice_network
    restart: always


networks:
  finservice_network:
    driver: bridge